### ISSUE TITLE
标签点击发送信息

### ISSUE THREAD

**Issue by qyj19920704** [open-dingtalk/dingtalk-card-examples#2]
你好,我希望实现
标签进行数据绑定
并且点击标签后自动把标签的value值当做消息发送(发送到聊天端,不是指定url回调),这个需求有实现吗?有哪些api可以参考吗?我在钉钉开放平台没找到这样的例子

**Comment by qyj19920704** [comment]
<img width="1512" alt="image" src="https://github.com/open-dingtalk/dingtalk-card-examples/assets/33174475/2e3293e8-1212-4088-b5ba-0917bc891d78">

**Comment by qyj19920704** [comment]
简单来说,就是个人消息如何通过接口发送呢?

**Comment by qyj19920704** [comment]
![image](https://github.com/open-dingtalk/dingtalk-card-examples/assets/33174475/13471261-8274-4669-a723-c9e969f5205b)
就是这样的效果

**Comment by ginping** [comment]
> 简单来说,就是个人消息如何通过接口发送呢?


您好，可以通过 dtmd 协议链接来实现，**dtmd 协议链接仅可以在由机器人发送的卡片消息中使用**。

演示卡片配置：

一个 markdown 组件、一个单个按钮组件：

<img width="451" alt="image" src="https://github.com/open-dingtalk/dingtalk-card-examples/assets/38139563/a36a7fa0-7b1d-41f3-b05f-02004bd52157">

演示卡片变量配置：

<img width="660" alt="image" src="https://github.com/open-dingtalk/dingtalk-card-examples/assets/38139563/5ea9418f-5cc6-43c1-accf-cef9742d2bf4">

按钮的显示条件配置：

<img width="394" alt="image" src="https://github.com/open-dingtalk/dingtalk-card-examples/assets/38139563/566b6cbb-5c0c-4d82-9356-b9e8e0248e26">

按钮的点击事件配置：

<img width="397" alt="image" src="https://github.com/open-dingtalk/dingtalk-card-examples/assets/38139563/80a953f4-e66e-4830-b8fa-dbe39290d692">

创建并投放卡片代码示例（Python 版本）：

```Python
class CardBotHandler(dingtalk_stream.ChatbotHandler):
    def __init__(self, logger: logging.Logger = logger):
        super(dingtalk_stream.ChatbotHandler, self).__init__()
        if logger:
            self.logger = logger

    async def process(self, callback: dingtalk_stream.CallbackMessage):
        incoming_message = dingtalk_stream.ChatbotMessage.from_dict(callback.data)
        content = (incoming_message.text.content or "").strip()
        self.logger.info(f"received message: {content}")

        card_template_id = "5f5ad786-de05-4628-b374-48f910288814.schema"
        
        text = "您好，帮我查询一下今天杭州的天气"
        card_data = {
            "markdown": "# hello markdown",
            "link": f"dtmd://dingtalkclient/sendMessage?content={text}"
        }
        if content == text:
            # 机器人收到 dtmd 消息做对应的处理
            card_data = {
                "markdown": "今天杭州的天气是晴"
            }

        card_instance = dingtalk_stream.CardReplier(
            self.dingtalk_client, incoming_message
        )
        card_instance_id = card_instance.create_and_deliver_card(
            card_template_id,
            dump_dict_attributes(card_data),
        )
        card_instances[card_instance_id] = card_instance

        self.logger.info(f"reply card {card_instance_id} {card_data}")

        return AckMessage.STATUS_OK, "OK"
```

实际效果：

<img width="850" alt="image" src="https://github.com/open-dingtalk/dingtalk-card-examples/assets/38139563/34f98a6b-30ea-4afb-bc0f-26d6b71809f2">

**Comment by qyj19920704** [comment]
感谢回答,一个月前已经通过这种方式解决了,只是标签还不能支持回调事件,要用按钮组件包一层,比较冗余

**Comment by qyj19920704** [comment]
> > 简单来说,就是个人消息如何通过接口发送呢?
> 
> 您好，可以通过 dtmd 协议链接来实现，**dtmd 协议链接仅可以在由机器人发送的卡片消息中使用**。
> 
> 演示卡片配置：
> 
> 一个 markdown 组件、一个单个按钮组件：
> 
> <img alt="image" width="451" src="https://private-user-images.githubusercontent.com/38139563/347657637-a36a7fa0-7b1d-41f3-b05f-02004bd52157.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTA1NDMsIm5iZiI6MTcyMTE5MDI0MywicGF0aCI6Ii8zODEzOTU2My8zNDc2NTc2MzctYTM2YTdmYTAtN2IxZC00MWYzLWIwNWYtMDIwMDRiZDUyMTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA0MjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMjA4NjY5NmYxZmVmNzNkYjMyMzQyMjlhYTExNTNkMWMyYmY2MjJjZWRhNTllM2NiZThkMTYxMjM5M2FkYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xlKky9WyTGoUTAxqNU7Rq2BZ0ru0jsL2mggtJ9u4jic">
> 演示卡片变量配置：
> 
> <img alt="image" width="660" src="https://private-user-images.githubusercontent.com/38139563/347657766-5ea9418f-5cc6-43c1-accf-cef9742d2bf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTA1NDMsIm5iZiI6MTcyMTE5MDI0MywicGF0aCI6Ii8zODEzOTU2My8zNDc2NTc3NjYtNWVhOTQxOGYtNWNjNi00M2MxLWFjY2YtY2VmOTc0MmQyYmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA0MjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNTU4MTM5Mzg4ZDgxOTZhMGU1MmZlZmQ5MjRlYWY1N2UzYjUwNTQ3NzFmZmNlMWVkOGU2MzM3NjQ0NDQxN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t5YMm_aG4Wpmv6EAId2JeFh1JVeWqcYpr2RqCC_Vhq4">
> 按钮的显示条件配置：
> 
> <img alt="image" width="394" src="https://private-user-images.githubusercontent.com/38139563/347657852-566b6cbb-5c0c-4d82-9356-b9e8e0248e26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTA1NDMsIm5iZiI6MTcyMTE5MDI0MywicGF0aCI6Ii8zODEzOTU2My8zNDc2NTc4NTItNTY2YjZjYmItNWMwYy00ZDgyLTkzNTYtYjllOGUwMjQ4ZTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA0MjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MThkYjQ2NzFmMTA4NmRiMTY3MGVmNWUwMzI1NTVkYzRjNzRkMDkzZTY3YmU4MzkyZjdhNDVmYTdkYmY1NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d44yy2P_GCTkqcZBkn_mZthTgqvm7jhP2BAvJlOFhMo">
> 按钮的点击事件配置：
> 
> <img alt="image" width="397" src="https://private-user-images.githubusercontent.com/38139563/347657910-80a953f4-e66e-4830-b8fa-dbe39290d692.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTA1NDMsIm5iZiI6MTcyMTE5MDI0MywicGF0aCI6Ii8zODEzOTU2My8zNDc2NTc5MTAtODBhOTUzZjQtZTY2ZS00ODMwLWI4ZmEtZGJlMzkyOTBkNjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA0MjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZDZmOTQzZWQzNTA1MjQ5YmY2ZWIyNjhhN2I1YmNjMmQ5N2NiMjNiNmUwM2Q0ODcyYTkxOGY4Y2M5MGM2ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3yqTrTxtfEDxysl3AU_J_kcbEeeRnMUUa_S44BlbeEA">
> 创建并投放卡片代码示例（Python 版本）：
> 
> ```python
> class CardBotHandler(dingtalk_stream.ChatbotHandler):
>     def __init__(self, logger: logging.Logger = logger):
>         super(dingtalk_stream.ChatbotHandler, self).__init__()
>         if logger:
>             self.logger = logger
> 
>     async def process(self, callback: dingtalk_stream.CallbackMessage):
>         incoming_message = dingtalk_stream.ChatbotMessage.from_dict(callback.data)
>         content = (incoming_message.text.content or "").strip()
>         self.logger.info(f"received message: {content}")
> 
>         card_template_id = "5f5ad786-de05-4628-b374-48f910288814.schema"
>         
>         text = "您好，帮我查询一下今天杭州的天气"
>         card_data = {
>             "markdown": "# hello markdown",
>             "link": f"dtmd://dingtalkclient/sendMessage?content={text}"
>         }
>         if content == text:
>             # 机器人收到 dtmd 消息做对应的处理
>             card_data = {
>                 "markdown": "今天杭州的天气是晴"
>             }
> 
>         card_instance = dingtalk_stream.CardReplier(
>             self.dingtalk_client, incoming_message
>         )
>         card_instance_id = card_instance.create_and_deliver_card(
>             card_template_id,
>             dump_dict_attributes(card_data),
>         )
>         card_instances[card_instance_id] = card_instance
> 
>         self.logger.info(f"reply card {card_instance_id} {card_data}")
> 
>         return AckMessage.STATUS_OK, "OK"
> ```
> 
> 实际效果：
> 
> <img alt="image" width="850" src="https://private-user-images.githubusercontent.com/38139563/347658307-34f98a6b-30ea-4afb-bc0f-26d6b71809f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTA1NDMsIm5iZiI6MTcyMTE5MDI0MywicGF0aCI6Ii8zODEzOTU2My8zNDc2NTgzMDctMzRmOThhNmItMzBlYS00YWZiLWJjMGYtMjZkNmI3MTgwOWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA0MjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMzM3YmQxOTY5N2EyZGI2NDdkYzdmY2U1ZDc5OGM0Y2M1M2E5ZWJlNWI2NzQxOGQ5NDAxMTQzMWIxNTVjMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P8F8xhW9vlONx9V2DGmS6I7VFwaWjz9ZkuMqunPgzlc">

感谢回答,一个月前已经通过这种方式解决了,只是标签还不能支持回调事件,要用按钮组件包一层,比较冗余

**Comment by badspider7** [comment]
mark
