### ISSUE TITLE
AI卡片不支持多人同时聊天,存在阻塞问题

### ISSUE THREAD

**Issue by qyj19920704** [open-dingtalk/dingtalk-card-examples#3]
<img width="811" alt="image" src="https://github.com/user-attachments/assets/67003d3f-a29d-474c-985e-5dc4e39a69ac">

**Comment by ginping** [comment]
Python 的 SDK 提供的投放卡片接口是同步的，但是启动 websocket 是异步的，异步函数里面执行耗时的同步任务会造成阻塞，预计 2 周内在 SDK 提供异步接口解决这个问题。

**Comment by ginping** [comment]
> <img alt="image" width="811" src="https://private-user-images.githubusercontent.com/33174475/352477304-67003d3f-a29d-474c-985e-5dc4e39a69ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjYwMjgsIm5iZiI6MTcyMjgyNTcyOCwicGF0aCI6Ii8zMzE3NDQ3NS8zNTI0NzczMDQtNjcwMDNkM2YtYTI5ZC00NzRjLTk4NWUtNWRjNGUzOWE2OWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAyNDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzM2FjYjY2MDMzMGUzZDYzNzk3NTIxMTEzYmZkYjhhZjY2ZjlkMDkwYTVhMjcwZjYyNzA1NDcwMzg4MDVhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zEeoNG1GszE8tKDLqqbMueh3SDm7V4fyXPv4X--IZHU">

更新 dingtalk-stream 版本到 0.21.0 以上，然后参考这个 commit 修改代码即可：https://github.com/open-dingtalk/dingtalk-card-examples/commit/ee39820bffe954b92223daab1c6e423ec853f0d9 #

**Comment by qyj19920704** [comment]
0.21.0版本可以了
